import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { SessionProvider } from "next-auth/react"
import "./globals.css";
import { getServerSession } from "next-auth";
import {authOptions} from "./api/auth/[...nextauth]/route"
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import ProductManager from "@/components/ProductManager";
import StartUpSubmitForm from "@/components/StartUpSubmitForm";
import { Header } from "next/dist/lib/load-custom-routes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable} bg-white`}>
      <body className="bg-white">
        <SessionProviderWrapper>
          {children}
          
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
