import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import  "./module.css"
import Header from "@/components/navbar/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`relative ${GeistSans.className} ${GeistMono.className}`}>
        <Header/>
        <div className="pt-24">  {children }</div>
      
        <div className="fixed right-2 bottom-2 z-50 text-xs text-gray-500 bg-white/80 px-3 py-1 rounded shadow">
          sponsored by Tewanay
        </div>
      </body>
    </html>
  );
}
